--- #YAML:1.0
name:               PostScript-PPD
version:            0.0203
abstract:           Read PostScript Printer Definition files
author:
    - Philip Gwyn <fil@localdomain>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Compress::Zlib:  2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
