---
abstract: 'Read PostScript Printer Definition files'
author:
  - 'Philip Gwyn <fil@localdomain>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.92, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PostScript-PPD
no_index:
  directory:
    - t
    - inc
requires:
  Compress::Zlib: '2'
version: '0.0206'
